import 'product.dart';

class SampleData {
  static List<Product> products = [
    // Meyveler
    Product(
      id: '1',
      name: 'İthal Muz',
      description: 'Taze ve lezzetli ithal muz',
      price: 94.99,
      imageUrl: 'assets/images/products/1.jpg',
      category: 'Meyve',
      categoryId: 1,
      rating: 4.6,
      reviewCount: 89,
      unit: 'kg',
    ),
    Product(
      id: '2',
      name: 'Şeftali',
      description: 'Tatlı ve sulu şeftali',
      price: 139.99,
      imageUrl: 'assets/images/products/2.jpg',
      category: 'Meyve',
      categoryId: 1,
      rating: 4.4,
      reviewCount: 67,
      unit: 'kg',
    ),
    Product(
      id: '3',
      name: 'Nektarin',
      description: 'Taze nektarin',
      price: 149.99,
      imageUrl: 'assets/images/products/3.jpg',
      category: 'Meyve',
      categoryId: 1,
      rating: 4.3,
      reviewCount: 45,
      unit: 'kg',
    ),
    Product(
      id: '4',
      name: 'Mini Karpuz',
      description: 'Küçük boy taze karpuz',
      price: 55.99,
      imageUrl: 'assets/images/products/4.jpg',
      category: 'Meyve',
      categoryId: 1,
      rating: 4.7,
      reviewCount: 123,
      unit: 'adet',
    ),
    Product(
      id: '5',
      name: 'Karpuz',
      description: 'Büyük boy taze karpuz',
      price: 84.99,
      imageUrl: 'assets/images/products/5.jpg',
      category: 'Meyve',
      categoryId: 1,
      rating: 4.8,
      reviewCount: 156,
      unit: 'adet',
    ),
    Product(
      id: '6',
      name: 'Kıraç Kavunu',
      description: 'Tatlı kıraç kavunu',
      price: 39.99,
      imageUrl: 'assets/images/products/6.jpg',
      category: 'Meyve',
      categoryId: 1,
      rating: 4.5,
      reviewCount: 78,
      unit: 'adet',
    ),
    Product(
      id: '7',
      name: 'Portakal Sıkmalık',
      description: 'Sıkma için özel portakal',
      price: 79.99,
      imageUrl: 'assets/images/products/7.jpg',
      category: 'Meyve',
      categoryId: 1,
      rating: 4.6,
      reviewCount: 92,
      unit: 'kg',
    ),
    Product(
      id: '8',
      name: 'Portakal',
      description: 'Taze portakal',
      price: 89.99,
      imageUrl: 'assets/images/products/8.jpg',
      category: 'Meyve',
      categoryId: 1,
      rating: 4.4,
      reviewCount: 134,
      unit: 'kg',
    ),
    Product(
      id: '9',
      name: 'Limon',
      description: 'Taze limon',
      price: 189.99,
      imageUrl: 'assets/images/products/9.jpg',
      category: 'Meyve',
      categoryId: 1,
      rating: 4.5,
      reviewCount: 67,
      unit: 'kg',
    ),
    Product(
      id: '10',
      name: 'Avakado Olgunlaşmamış',
      description: 'Olgunlaşmamış avakado',
      price: 52.99,
      imageUrl: 'assets/images/products/10.jpg',
      category: 'Meyve',
      categoryId: 1,
      rating: 4.2,
      reviewCount: 34,
      unit: 'kg',
    ),
    Product(
      id: '11',
      name: 'Avakado Olgun',
      description: 'Olgun ve yemeye hazır avakado',
      price: 58.99,
      imageUrl: 'assets/images/products/11.jpg',
      category: 'Meyve',
      categoryId: 1,
      rating: 4.6,
      reviewCount: 89,
      unit: 'kg',
    ),
    Product(
      id: '12',
      name: 'Mango',
      description: 'Tatlı ve sulu mango',
      price: 94.99,
      imageUrl: 'assets/images/products/12.jpg',
      category: 'Meyve',
      categoryId: 1,
      rating: 4.7,
      reviewCount: 156,
      unit: 'kg',
    ),
    Product(
      id: '13',
      name: 'Anjenik Erik',
      description: 'Taze anjenik erik',
      price: 149.99,
      imageUrl: 'assets/images/products/13.jpg',
      category: 'Meyve',
      categoryId: 1,
      rating: 4.4,
      reviewCount: 78,
      unit: 'kg',
    ),
    Product(
      id: '14',
      name: 'Ejder Meyvesi',
      description: 'Egzotik ejder meyvesi',
      price: 79.99,
      imageUrl: 'assets/images/products/14.jpg',
      category: 'Meyve',
      categoryId: 1,
      rating: 4.8,
      reviewCount: 234,
      unit: 'adet',
    ),
    Product(
      id: '15',
      name: 'Yaban Mersini',
      description: 'Taze yaban mersini',
      price: 99.99,
      imageUrl: 'assets/images/products/15.jpg',
      category: 'Meyve',
      categoryId: 1,
      rating: 4.6,
      reviewCount: 123,
      unit: 'kg',
    ),
    Product(
      id: '16',
      name: 'Akça Armut',
      description: 'Tatlı akça armut',
      price: 119.99,
      imageUrl: 'assets/images/products/16.jpg',
      category: 'Meyve',
      categoryId: 1,
      rating: 4.5,
      reviewCount: 89,
      unit: 'kg',
    ),
    Product(
      id: '17',
      name: 'Elma',
      description: 'Taze elma',
      price: 119.99,
      imageUrl: 'assets/images/products/17.jpg',
      category: 'Meyve',
      categoryId: 1,
      rating: 4.4,
      reviewCount: 167,
      unit: 'kg',
    ),
    // Sebzeler
    Product(
      id: '18',
      name: 'Patates Ekonomik',
      description: 'Ekonomik fiyatlı patates',
      price: 11.99,
      imageUrl: 'assets/images/products/18.jpg',
      category: 'Sebze',
      categoryId: 2,
      rating: 4.3,
      reviewCount: 234,
      unit: 'kg',
    ),
    Product(
      id: '19',
      name: 'Patates',
      description: 'Taze patates',
      price: 13.99,
      imageUrl: 'assets/images/products/19.jpg',
      category: 'Sebze',
      categoryId: 2,
      rating: 4.5,
      reviewCount: 189,
      unit: 'kg',
    ),
    Product(
      id: '20',
      name: 'Patates Küçük',
      description: 'Küçük boy taze patates',
      price: 59.99,
      imageUrl: 'assets/images/products/20.jpg',
      category: 'Sebze',
      categoryId: 2,
      rating: 4.4,
      reviewCount: 67,
      unit: 'kg',
    ),
    Product(
      id: '21',
      name: 'Soğan Organik',
      description: 'Organik soğan',
      price: 9.99,
      imageUrl: 'assets/images/products/21.jpg',
      category: 'Sebze',
      categoryId: 2,
      rating: 4.6,
      reviewCount: 145,
      unit: 'kg',
    ),
    Product(
      id: '22',
      name: 'Kuru Soğan',
      description: 'Taze kuru soğan',
      price: 10.99,
      imageUrl: 'assets/images/products/22.jpg',
      category: 'Sebze',
      categoryId: 2,
      rating: 4.4,
      reviewCount: 178,
      unit: 'kg',
    ),
    Product(
      id: '23',
      name: 'Domates',
      description: 'Taze domates',
      price: 29.99,
      imageUrl: 'assets/images/products/23.jpg',
      category: 'Sebze',
      categoryId: 2,
      rating: 4.7,
      reviewCount: 267,
      unit: 'kg',
    ),
    Product(
      id: '24',
      name: 'Kokteyl Domates',
      description: 'Küçük boy kokteyl domates',
      price: 79.99,
      imageUrl: 'assets/images/products/24.jpg',
      category: 'Sebze',
      categoryId: 2,
      rating: 4.8,
      reviewCount: 189,
      unit: 'kg',
    ),
    Product(
      id: '25',
      name: 'Pembe Domates',
      description: 'Tatlı pembe domates',
      price: 39.99,
      imageUrl: 'assets/images/products/25.jpg',
      category: 'Sebze',
      categoryId: 2,
      rating: 4.6,
      reviewCount: 123,
      unit: 'kg',
    ),
    Product(
      id: '26',
      name: 'Salkım Domates',
      description: 'Salkım halinde domates',
      price: 49.99,
      imageUrl: 'assets/images/products/26.jpg',
      category: 'Sebze',
      categoryId: 2,
      rating: 4.5,
      reviewCount: 89,
      unit: 'kg',
    ),
    Product(
      id: '27',
      name: 'Çengelköy Salatalık',
      description: 'Taze Çengelköy salatalığı',
      price: 59.99,
      imageUrl: 'assets/images/products/27.jpg',
      category: 'Sebze',
      categoryId: 2,
      rating: 4.7,
      reviewCount: 156,
      unit: 'kg',
    ),
    Product(
      id: '28',
      name: 'Salatalık',
      description: 'Taze salatalık',
      price: 37.99,
      imageUrl: 'assets/images/products/28.jpg',
      category: 'Sebze',
      categoryId: 2,
      rating: 4.4,
      reviewCount: 234,
      unit: 'kg',
    ),
    Product(
      id: '29',
      name: 'Sivri Biber',
      description: 'Taze sivri biber',
      price: 49.99,
      imageUrl: 'assets/images/products/29.jpg',
      category: 'Sebze',
      categoryId: 2,
      rating: 4.5,
      reviewCount: 167,
      unit: 'kg',
    ),
    Product(
      id: '30',
      name: 'Tatlı Kıl Sivri Biber',
      description: 'Tatlı kıl sivri biber',
      price: 119.99,
      imageUrl: 'assets/images/products/30.jpg',
      category: 'Sebze',
      categoryId: 2,
      rating: 4.6,
      reviewCount: 45,
      unit: 'kg',
    ),
    Product(
      id: '31',
      name: 'Çarliston Biber',
      description: 'Taze Çarliston biberi',
      price: 54.99,
      imageUrl: 'assets/images/products/31.jpg',
      category: 'Sebze',
      categoryId: 2,
      rating: 4.3,
      reviewCount: 67,
      unit: 'kg',
    ),
    Product(
      id: '32',
      name: 'Dolmalık Biber',
      description: 'Dolma için özel biber',
      price: 44.99,
      imageUrl: 'assets/images/products/32.jpg',
      category: 'Sebze',
      categoryId: 2,
      rating: 4.5,
      reviewCount: 78,
      unit: 'kg',
    ),
    Product(
      id: '33',
      name: 'Köy Biberi',
      description: 'Doğal köy biberi',
      price: 44.99,
      imageUrl: 'assets/images/products/33.jpg',
      category: 'Sebze',
      categoryId: 2,
      rating: 4.4,
      reviewCount: 56,
      unit: 'kg',
    ),
    Product(
      id: '34',
      name: 'Kapya Biber',
      description: 'Tatlı kapya biberi',
      price: 68.99,
      imageUrl: 'assets/images/products/34.jpg',
      category: 'Sebze',
      categoryId: 2,
      rating: 4.6,
      reviewCount: 89,
      unit: 'kg',
    ),
    Product(
      id: '35',
      name: 'Taze Fasulye',
      description: 'Taze yeşil fasulye',
      price: 129.99,
      imageUrl: 'assets/images/products/35.jpg',
      category: 'Sebze',
      categoryId: 2,
      rating: 4.5,
      reviewCount: 67,
      unit: 'kg',
    ),
    Product(
      id: '36',
      name: 'Barbunya',
      description: 'Taze barbunya fasulyesi',
      price: 139.99,
      imageUrl: 'assets/images/products/36.jpg',
      category: 'Sebze',
      categoryId: 2,
      rating: 4.4,
      reviewCount: 45,
      unit: 'kg',
    ),
    Product(
      id: '37',
      name: 'Kabak',
      description: 'Taze kabak',
      price: 39.99,
      imageUrl: 'assets/images/products/37.jpg',
      category: 'Sebze',
      categoryId: 2,
      rating: 4.3,
      reviewCount: 78,
      unit: 'adet',
    ),
    Product(
      id: '38',
      name: 'Patlıcan',
      description: 'Taze patlıcan',
      price: 42.99,
      imageUrl: 'assets/images/products/38.jpg',
      category: 'Sebze',
      categoryId: 2,
      rating: 4.4,
      reviewCount: 89,
      unit: 'kg',
    ),
    Product(
      id: '39',
      name: 'Mısır',
      description: 'Taze mısır',
      price: 24.99,
      imageUrl: 'assets/images/products/39.jpg',
      category: 'Sebze',
      categoryId: 2,
      rating: 4.6,
      reviewCount: 123,
      unit: 'adet',
    ),
    Product(
      id: '40',
      name: 'Havuç',
      description: 'Taze havuç',
      price: 54.99,
      imageUrl: 'assets/images/products/40.jpg',
      category: 'Sebze',
      categoryId: 2,
      rating: 4.5,
      reviewCount: 167,
      unit: 'kg',
    ),
    Product(
      id: '41',
      name: 'Pancar',
      description: 'Taze pancar',
      price: 59.99,
      imageUrl: 'assets/images/products/41.jpg',
      category: 'Sebze',
      categoryId: 2,
      rating: 4.3,
      reviewCount: 45,
      unit: 'kg',
    ),
    Product(
      id: '42',
      name: 'Sarımsak',
      description: 'Taze sarımsak',
      price: 63.99,
      imageUrl: 'assets/images/products/42.jpg',
      category: 'Sebze',
      categoryId: 2,
      rating: 4.7,
      reviewCount: 189,
      unit: 'kg',
    ),
    Product(
      id: '43',
      name: 'Zencefil',
      description: 'Taze zencefil',
      price: 58.99,
      imageUrl: 'assets/images/products/43.jpg',
      category: 'Sebze',
      categoryId: 2,
      rating: 4.6,
      reviewCount: 78,
      unit: 'kg',
    ),
    Product(
      id: '44',
      name: 'Mor Soğan',
      description: 'Taze mor soğan',
      price: 54.99,
      imageUrl: 'assets/images/products/44.jpg',
      category: 'Sebze',
      categoryId: 2,
      rating: 4.4,
      reviewCount: 67,
      unit: 'kg',
    ),
    Product(
      id: '45',
      name: 'Marul',
      description: 'Taze marul',
      price: 49.99,
      imageUrl: 'assets/images/products/45.jpg',
      category: 'Sebze',
      categoryId: 2,
      rating: 4.5,
      reviewCount: 145,
      unit: 'adet',
    ),
    Product(
      id: '46',
      name: 'Kıvırcık Marul',
      description: 'Taze kıvırcık marul',
      price: 44.99,
      imageUrl: 'assets/images/products/46.jpg',
      category: 'Sebze',
      categoryId: 2,
      rating: 4.6,
      reviewCount: 123,
      unit: 'adet',
    ),
    Product(
      id: '47',
      name: 'Atom Marul',
      description: 'Küçük boy atom marul',
      price: 69.99,
      imageUrl: 'assets/images/products/47.jpg',
      category: 'Sebze',
      categoryId: 2,
      rating: 4.7,
      reviewCount: 89,
      unit: 'adet',
    ),
    Product(
      id: '48',
      name: 'Maydanoz Temizlenmiş',
      description: 'Temizlenmiş maydanoz',
      price: 29.99,
      imageUrl: 'assets/images/products/48.jpg',
      category: 'Sebze',
      categoryId: 2,
      rating: 4.5,
      reviewCount: 67,
      unit: 'demet',
    ),
    Product(
      id: '49',
      name: 'Maydanoz',
      description: 'Taze maydanoz',
      price: 17.99,
      imageUrl: 'assets/images/products/49.jpg',
      category: 'Sebze',
      categoryId: 2,
      rating: 4.4,
      reviewCount: 134,
      unit: 'demet',
    ),
    Product(
      id: '50',
      name: 'Roka Temizlenmiş',
      description: 'Temizlenmiş roka',
      price: 29.99,
      imageUrl: 'assets/images/products/50.jpg',
      category: 'Sebze',
      categoryId: 2,
      rating: 4.6,
      reviewCount: 78,
      unit: 'demet',
    ),
    Product(
      id: '51',
      name: 'Roka',
      description: 'Taze roka',
      price: 24.99,
      imageUrl: 'assets/images/products/51.jpg',
      category: 'Sebze',
      categoryId: 2,
      rating: 4.5,
      reviewCount: 156,
      unit: 'demet',
    ),
    Product(
      id: '52',
      name: 'Nane Temizlenmiş',
      description: 'Temizlenmiş nane',
      price: 29.99,
      imageUrl: 'assets/images/products/52.jpg',
      category: 'Sebze',
      categoryId: 2,
      rating: 4.4,
      reviewCount: 45,
      unit: 'demet',
    ),
    Product(
      id: '53',
      name: 'Nane',
      description: 'Taze nane',
      price: 22.99,
      imageUrl: 'assets/images/products/53.jpg',
      category: 'Sebze',
      categoryId: 2,
      rating: 4.6,
      reviewCount: 123,
      unit: 'demet',
    ),
    Product(
      id: '54',
      name: 'Dereotu',
      description: 'Taze dereotu',
      price: 19.99,
      imageUrl: 'assets/images/products/54.jpg',
      category: 'Sebze',
      categoryId: 2,
      rating: 4.5,
      reviewCount: 89,
      unit: 'demet',
    ),
    Product(
      id: '55',
      name: 'Taze Soğan Temizlenmiş',
      description: 'Temizlenmiş taze soğan',
      price: 47.99,
      imageUrl: 'assets/images/products/55.jpg',
      category: 'Sebze',
      categoryId: 2,
      rating: 4.7,
      reviewCount: 67,
      unit: 'demet',
    ),
    Product(
      id: '56',
      name: 'Taze Soğan',
      description: 'Taze soğan',
      price: 36.99,
      imageUrl: 'assets/images/products/56.jpg',
      category: 'Sebze',
      categoryId: 2,
      rating: 4.6,
      reviewCount: 145,
      unit: 'demet',
    ),
    Product(
      id: '57',
      name: 'Yedikule Marulu',
      description: 'Küçük boy Yedikule marulu',
      price: 79.99,
      imageUrl: 'assets/images/products/57.jpg',
      category: 'Sebze',
      categoryId: 2,
      rating: 4.8,
      reviewCount: 234,
      unit: 'adet',
    ),
  ];

  static List<String> categories = [
    'Meyve',
    'Sebze',
  ];

  static List<Product> getProductsByCategory(String category) {
    return products.where((product) => product.category == category).toList();
  }

  static List<Product> getProductsByCategoryId(int categoryId) {
    return products.where((product) => product.categoryId == categoryId).toList();
  }

  static List<Product> getFeaturedProducts() {
    return products.where((product) => product.rating >= 4.5).toList();
  }
} 