// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9wQ_J8XSMbrM6k2IAjq2MBvspTrXt8Js',
    appId: '1:744650264368:web:0de0026a15b6086da302f5',
    messagingSenderId: '744650264368',
    projectId: 'marketapp-e230a',
    authDomain: 'marketapp-e230a.firebaseapp.com',
    storageBucket: 'marketapp-e230a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuPCiWO7LPk1jvbWc0RDQpl45XQdQy-VM',
    appId: '1:744650264368:android:adcc51adec1a6ac4a302f5',
    messagingSenderId: '744650264368',
    projectId: 'marketapp-e230a',
    storageBucket: 'marketapp-e230a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwXFWlFT9hxJ5PWYRIgZ16bm-OEY_sIEc',
    appId: '1:744650264368:ios:2f4e68c98fc8dd5ba302f5',
    messagingSenderId: '744650264368',
    projectId: 'marketapp-e230a',
    storageBucket: 'marketapp-e230a.firebasestorage.app',
    iosBundleId: 'com.example.marketApp0',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwXFWlFT9hxJ5PWYRIgZ16bm-OEY_sIEc',
    appId: '1:744650264368:ios:2f4e68c98fc8dd5ba302f5',
    messagingSenderId: '744650264368',
    projectId: 'marketapp-e230a',
    storageBucket: 'marketapp-e230a.firebasestorage.app',
    iosBundleId: 'com.example.marketApp0',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9wQ_J8XSMbrM6k2IAjq2MBvspTrXt8Js',
    appId: '1:744650264368:web:986de4538cff2154a302f5',
    messagingSenderId: '744650264368',
    projectId: 'marketapp-e230a',
    authDomain: 'marketapp-e230a.firebaseapp.com',
    storageBucket: 'marketapp-e230a.firebasestorage.app',
  );
}
